### ISSUE TITLE
Twitter Widget displays filler tweets when account access is revoked then granted again

### ISSUE THREAD

**Issue by jungeunyoon** [Rise-Vision/rise-twitter#60]
### What is the expected behavior?
When a user revokes or grants Twitter access to a Twitter Widget it should display either filler tweets when revoked or actual tweets from the attached handle when granted. 

### What is the actual behavior?
When a user revokes Twitter access then grants it, it always displays filler tweets instead of the actual tweets from the handle connected to the Twitter Widget instance.

### What steps can be taken to replicate the problem?
1. On Twitter Widget, revoke access and publish
2. On Twitter Widget, grant access and publish

It should display filler tweets

**Comment by santiagonoguez** [comment]
Fix in stable with rollout at 100%, closing this issue.
