### ISSUE TITLE
Twitter widget not loading feed on specific Displays

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-twitter#62]
**Expected Behavior**
Displays playing Presentations containing the twitter widget should show a feed if the twitter widget is authorized and a twitter handle is provided.

**Actual Behavior**
On a specific Display, the twitter widget does not load the feed even though the widget is authorized and a valid twitter handle is provided.

**Step to reproduce:**
Not reproducible on my own hardware. 
Only happens on a specific Display so far.

**Comment by santiagonoguez** [comment]
Rolled out at 100%
