### ISSUE TITLE
Endpoints reporting rise-twitter-widget-deliberately skipped

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-twitter#70]

**Comment by stulees** [comment]
@alanclayton Can you clarify and provide more information with this issue? Thanks

**Comment by alanclayton** [comment]
@stulees I reviewed with @ByronDarlison and we are not going to pursue fixing this defect. We need to be telling users if there is an error preventing their content from being shown and provide instructions for how to resolve. The foundation for doing this will come with the logging epic.

**Comment by stulees** [comment]
@alanclayton Okay thanks. Can we close this issue then?

**Comment by alanclayton** [comment]
@stulees No, it should stay open until we are doing what I describe above. I think you should set the target date to be the end of Oct. At that time assess where we are at with delivering the work to close update accordingly. Thanks

**Comment by stulees** [comment]
@alanclayton Got it, okay will do, thanks

**Comment by ezequielc** [comment]
@alanclayton The original idea of showing errors to users in Apps has decreased in priority in favour of our weekly uptime analysis and more specific actions. In addition, I am pursuing a pitch to notify users by email about "action required" errors. 

Given that and also the fact that this defect has been blocked for almost 1 year, I am proposing we close it. There are other blocked defects that fall into the same category, so I would like to clean them up. Let me know if good with you. Thanks!

**Comment by alanclayton** [comment]
@ezequielc Agreed. Thanks

**Comment by ezequielc** [comment]
@alanclayton Thanks!

@stulees fyi, I will be closing a few of the blocked defects.
